### ISSUE TITLE
[Feature Request] Options to order library

### ISSUE THREAD

**Issue by Forgenn** [Suwayomi/Tachidesk-WebUI#11]
## What feature should be added to Tachidesk?
The library should have the possibility to be ordered in different ways, by the last chapter uploaded, by date added, alphabetically etc..

##  Why/Project's Benefit/Existing Problem
Currently, the library is ordered by the internal manga id, which makes looking for updates difficult.

**Comment by Robonau** [comment]
i currently have a user-script to reorder manga after everything has loaded, though as expected it breaks some functionality (searching) and is certainly not ideal

**Comment by schroda** [comment]
outdated (done)
