### ISSUE TITLE
[Feature Request] Sort Library

### ISSUE THREAD

**Issue by Nathan-MV** [Suwayomi/Tachidesk-WebUI#120]
## What feature should be added to Tachidesk?
In the manga page, you would have the ability to update your reading status, that would be the ones below.
In the Library, the ability to sort in (Reading, Plan To Read, Completed, On Hold, Re-reading, Dropped).

##  Why/Project's Benefit/Existing Problem
Fast search of the mangas you are currently (Reading, Plan To Read, Completed, On Hold, Re-reading, Dropped).

**Comment by AriaMoradi** [comment]
You can already do this, create the appropriate categories from settings, then edit the categories of a manga from the top right context menu button

**Comment by schroda** [comment]
> You can already do this, create the appropriate categories from settings, then edit the categories of a manga from the top right context menu button

.
