### ISSUE TITLE
[The Last Page is missing] <Every chapter i read in Tachidesk doesn't have the last page of the chapter>

### ISSUE THREAD

**Issue by Carmine23000** [Suwayomi/Tachidesk-WebUI#121]
## Device information
- Tachidesk version: v0.6.0-r1056-win64
- Server Operating System: Windows 10
- Server Desktop Environment: N/A
- Client Operating System: Windows 10
- Client Web Browser: Google Chrome 96.0.4664.110

When i read a chapter, the number 1 page is black and all pages go to the next number (so if i use tachiyomi the first page is in tachidesk the second one), but the number of pages remains the same because the last one just disappear...
Please help me :/

**Comment by schroda** [comment]
outdated
