### ISSUE TITLE
[Bug] <Pains to do search every time>

### ISSUE THREAD

**Issue by thisisnaveen** [Suwayomi/Tachidesk-WebUI#122]
When I search in a source for manga or comics after selecting and going back the search results always disappear and the searching process is being repeated. It does not happen in tachiyomi mobile app.  There the search results are kept after going back to search option. I dunno whether it is caching or memory issues but it pains to do a search after selecting the wrong manga for the same keyword every time. This issue also raised in discord server with picture reference. Please, fix it.

**Comment by Robonau** [comment]
having now moved search to inside of browse this should have been fixed

**Comment by schroda** [comment]
works in latest preview version
