### ISSUE TITLE
[Feature Request] Option to fit pages vertically on the screen

### ISSUE THREAD

**Issue by Miyazono1** [Suwayomi/Tachidesk-WebUI#13]
## What feature should be added to Tachidesk?
Add on option in the reader settings to fit pages on the screen vertically so you don't need to scroll to read them.

##  Why/Project's Benefit/Existing Problem
i personally think it's more convenient that way.

**Comment by ntbm** [comment]
@AriaMoradi Want this as well. Will start working on it.

**Comment by zFerry98** [comment]
I can't find the above option.
0.6.3 release.
![image](https://user-images.githubusercontent.com/17975351/177055272-40e198e5-5f16-4c95-94d1-8c88a881b1ca.png)

**Comment by schroda** [comment]
done with https://github.com/Suwayomi/Tachidesk-WebUI/pull/323
