### ISSUE TITLE
[Bug] NEW PAGE THE PAGE NOT COMING BACK UP

### ISSUE THREAD

**Issue by HANU69** [Suwayomi/Tachidesk-WebUI#180]
whenever it Tachidesk we move to a new page the scroll bar stays and the bottom and not comes up we need to manually drag it up then start reading it .I see it as a problem because it is not with the flow. is there a way that the page positioning comes back up after we move to the new page. would be highly appreciable if help provided

**Comment by AriaMoradi** [comment]
Sorry, I'm sleepy :)

**Comment by HANU69** [comment]
i am not all into coding for now . i hope it can get fixed

**Comment by HANU69** [comment]
so what to do now

**Comment by Robonau** [comment]
> so what to do now

wait for someone that wants to fix it

**Comment by HANU69** [comment]
oh ok
