### ISSUE TITLE
[Bug] responsive ui issues in the sources search page for high resolution

### ISSUE THREAD

**Issue by infix** [Suwayomi/Tachidesk-WebUI#207]
## Steps to reproduce
1. open the sources browsing on 4k (issue also occurs on 1440p)
2. infinite scroll is broken because only half of the screen are filled. you have to zoom in to 300% or higher then scroll for it to fetch more results

### Expected behavior
the entire screen should be filled with results, and it should scrolling should fetch more results

## Other details
This should be an easy fix, and I'll try fix it when I've got some free-time

**Comment by martinek** [comment]
I know about this issue. It happens, because the "fetchMore" code is only called onScroll, but since the screen is not filled, you cannot scroll.

I planned on fixing this, but the whole screen and data fetching in it needs some cleanup. But you are more then welcome to take a shot at it.

**Comment by schroda** [comment]
works in latest preview version
