### ISSUE TITLE
[Bug] access error on ipad

### ISSUE THREAD

**Issue by mayziran** [Suwayomi/Tachidesk-WebUI#234]
## Device information
- Tachidesk version: 0.6.6
- Server Operating System: docker
- Server Desktop Environment: N/A 
- Server JVM version: Bundled with Suwayomi Docker image.
- Client Operating System: ios 16.3 ipad
- Client Web Browser: all browser include safari chrome firefox

## Steps to reproduce
1. docker run -d\
   --restart unless-stopped \
   --name tachidesk \
   -p 14567:4567 \
   -e TZ=Asia/Shanghai \
   -v $(pwd)/data:/./home/suwayomi/.local/share/Tachidesk \
   ghcr.io/suwayomi/tachidesk
2. change server.conf，set username and password
3. Open web browser in my ipad, navigate to 192.168.0.158:14567

### Expected behavior
Normal use

### Actual behavior
I first log in with safari, and I see the comics on my home page, but every time I click on other menus, I will be prompted to enter a username and password. I tried chrome and firefox,  as long as it's the same on ipad.
## Other details
But on both my computer and android phone, it only needs to log in once to use normally, what a strange problem。

**Comment by AriaMoradi** [comment]
this is a browser feature, your browser doesn't save the username and password probably

**Comment by mayziran** [comment]
The strange thing is that every browser on my ipad has this problem. I remember that all ios browsers use the same kernel. I use an ipad pro 2022 11-inch, the latest system.
After I enter the password for the first time, I can even continue to browse the comics, but every time I click the menu, it will pop up to ask me to enter the password, and I can click Cancel multiple times until I enter the comic browsing page. I seem to have found a suspected reason https://stackoverflow.com/questions/58856167/basic-authentication-not-working-in-safari

**Comment by schroda** [comment]
https://github.com/Suwayomi/Tachidesk-WebUI/issues/234#issuecomment-1426257184
