### ISSUE TITLE
[Bug] Next Chapter loaded on refresh

### ISSUE THREAD

**Issue by Pikcee** [Suwayomi/Tachidesk-WebUI#243]
## Device information
- Tachidesk version: v0.7.0-r983-x64
- Client Web Browser: Firefox v110

## Steps to reproduce
1. Set the reader type to Webtoon or Continuous Vertical
2. Enable "Load next chapter at ending"
3. Scroll to half the chapter and refresh the page

### behavior
Instead of refreshing the current page next chapter is loaded!

## Other details
Refresh a page multiple times you'll notice the scroll bar start from the end of the page and then jumps up
keep refreshing and the page position will keep going up little by little with every refresh, I believe this is related.
this behavior will also be noticed in-case you are using an extension to auto-discard idle tabs, and after a crash.
in my case as I tend to keep tons of tabs open, this bug messes most of them.

**Comment by schroda** [comment]
unable to reproduce
