### ISSUE TITLE
[Feature Request] Reader Layout and Shortcut Suggestion

### ISSUE THREAD

**Issue by BaccanoMob** [Suwayomi/Tachidesk-WebUI#27]
![image](https://user-images.githubusercontent.com/82655889/120249581-acc09400-c27b-11eb-8c56-702f07f001a4.png)

The "X" in the reader settings is kind of confusing and makes me think I am closing the sidebar while I am closing the manga itself.

It would be cool to have the "X" as separate button above ">", something like this.
![image](https://user-images.githubusercontent.com/82655889/120249789-4d16b880-c27c-11eb-9b8a-9ef447c97e34.png).

Also, it be cool if you could keymap Esc button as to go back as shortcut as well (Think it would be ideal since electron does not have the arrows as in browser).

**Comment by AriaMoradi** [comment]
reader layout was changed in #21, open another issue for your hotkey requests.
