### ISSUE TITLE
[Bug] Returning to the previous chapter leads to its first page instead of the last

### ISSUE THREAD

**Issue by Release** [Suwayomi/Tachidesk-WebUI#280]
## Device information
- Tachidesk version: 0.7.0
- Server Operating System: Manjaro 22.1.0

## Steps to reproduce
1. On the first page of the chapter, click on the left side of the image or press the Left key on the keyboard

### Expected behavior
Jump to the last page of the previous chapter

### Actual behavior
Jump to the first page of the previous chapter

## Other details
The current implementation of initializing the 'initialPage' variable in the 'src/screens/Reader.tsx' file results in this error:
lines 285-286
```
    // last page, also probably read = true, we will load the first page.
    const initialPage = pageToScrollTo ?? (chapter.lastPageRead === chapter.pageCount - 1 ? 0 : chapter.lastPageRead);
```
also, maybe lines 214-217 don't make sense:
```
if (data.lastPageRead === data.pageCount - 1) {
    // last page, also probably read = true, we will load the first page.
    setCurPage(0);
} else setCurPage(data.lastPageRead);
```
because after the current page is set by line 94 in the file 'src/components/reader/pager/PagedPager.tsx':
```
// scroll last read page into view when initialPage changes
changePage(initialPage);
```

**Comment by AriaMoradi** [comment]
This is expected behavior, when you finish a chapter it is set as read and when a chapter is read then we should ignore the last page read value and open the first page of the chapter.

**Comment by Release** [comment]
> This is expected behavior, when you finish a chapter it is set as read and when a chapter is read then we should ignore the last page read value and open the first page of the chapter.

But then it is impossible to rewind one or two pages back to the previous chapter. That is, I went back one page to the previous chapter, and eventually returned to the first. And then you have to scroll forward through all the pages.

**Comment by schroda** [comment]
> And then I have to flip forward through all the chapter pages

you can jump to a specific page by selecting it in the dropdown of the reader navigation bar

**Comment by Release** [comment]
> you can jump to a specific page by selecting it in the dropdown of the reader navigation bar

This is understandable, but this behavior is unintuitive and unfriendly. No application that I know of skips over multiple pages when it expects to return to one. Tachiyomi doesn't act like that either.
