### ISSUE TITLE
[Bug] Install External Extension add icon is not working

### ISSUE THREAD

**Issue by phanirithvij** [Suwayomi/Tachidesk-WebUI#30]
The add button isn't working for some reason. But drag-drop apk works.
I looked at the event listeners attached to the input element and there was the only one and it was `invalid`.

[Screenshot](https://user-images.githubusercontent.com/29627898/133745005-bf09ac2e-457a-430b-80cf-ef78baafa2ad.png)

[dev-tools-output-screenshot](https://user-images.githubusercontent.com/29627898/133745167-41a3a2f1-5e2a-481b-b6a5-639c6c0f420e.png)

I'm guessing this might not be getting registered?
https://github.com/Suwayomi/Tachidesk-WebUI/commit/ea63469e0ea8f96eb240a20679a9b1231f54b640#diff-438d2da1a577d3b1dae4fdf7bb51f5e768e65f3128042ac219c3ecde1e26c0ddR141

**Comment by AriaMoradi** [comment]
I can't reproduce this on chrome. which version of the Server/WebUI are you testing?
Do you have the same issue with chrome? It might be something wrong with Brave?

**Comment by phanirithvij** [comment]
```go
Tachidesk:		v 0.5.0 revision r 911
WebUI:			built-in version

Edition:		Windows 10 Home Single Language
OS build:		19042.1237

Brave: 			1.29.81 Chromium: 93.0.4577.82 (Official Build) (64-bit)
Firefox: 		92.0 (64-bit)
Google Chrome Beta:	94.0.4606.50 (Official Build) beta (64-bit) (cohort: Beta)
Edge:			93.0.961.47 (Official build) (64-bit)
```
Was able to reproduce on Chrome, Brave, Firefox, and Edge.

It was because of `updateTriggerHolder, extensionsRaw, extensions` logic.

The render happens initially as `<h3>loading...</h3>` and then the `useEffect` with the 'change' `addEventListener` gets called. 
And then on this `input?.addEventListener` input will be `null` until another `useEffect` call happens.

I don't know why you can't reproduce this, logically it should happen 100% of the time.

I got it to work by adding the `extensions` variable to the `useEffect`'s dependency array.

```jsx
useEffect(() => {
    // ...
    const input = document.getElementById('external-extension-file');
    input?.addEventListener('change', changeHandler);

    return () => {
        // ...
    };
}, [extensions]); // This
```

**Comment by AriaMoradi** [comment]
open a pull request with your fix
