### ISSUE TITLE
[Feature Request] Permanent Sidebar instead of Hidden Sidebar

### ISSUE THREAD

**Issue by voltrare** [Suwayomi/Tachidesk-WebUI#34]
Instead of a hidden sidebar why don't we have a permanent sidebar while browsing the app, 
like how they show servers on discord with the same/similar logos as Tachi

For desktop that it be might be convenient and 
Could be hidden for small window/phone or when reading a manga

**Comment by AriaMoradi** [comment]
closed in v0.6.0
