### ISSUE TITLE
[question] images width, local path

### ISSUE THREAD

**Issue by hell-kun** [Suwayomi/Tachidesk-WebUI#364]
is there a deafult forced width? and can i disable it? or change it at least?
i got images on 720 width , when i opened the chapter with the software forced it to become 800 which worsen the quality

can i change the local path?
it's located on the C-driver, which is already full with other things, so i would like to move it to other driver

also please add a question label if that's OK

thank you.

**Comment by schroda** [comment]
> can i change the local path?
it's located on the C-driver, which is already full with other things, so i would like to move it to other driver

https://github.com/Suwayomi/Tachidesk-Server/wiki/Configuring-Tachidesk-Server#my-tachidesk-data-directorydownloads-size-is-getting-to-big

> is there a deafult forced width? and can i disable it? or change it at least?
i got images on 720 width , when i opened the chapter with the software forced it to become 800 which worsen the quality

pages currently have a min width of 50% of the screen and it's not possible to deactivate

**Comment by schroda** [comment]
related to (image size) https://github.com/Suwayomi/Tachidesk-WebUI/issues/134

**Comment by hell1231** [comment]
> > can i change the local path?
> > it's located on the C-driver, which is already full with other things, so i would like to move it to other driver
> 
> https://github.com/Suwayomi/Tachidesk-Server/wiki/Configuring-Tachidesk-Server#my-tachidesk-data-directorydownloads-size-is-getting-to-big
> 
> > is there a deafult forced width? and can i disable it? or change it at least?
> > i got images on 720 width , when i opened the chapter with the software forced it to become 800 which worsen the quality
> 
> pages currently have a min width of 50% of the screen and it's not possible to deactivate

can you explain what to do exactly? 
i want the local path to be changed to "D:\Manga"

**Comment by schroda** [comment]
you change "server.downloadsPath" in the config file to "D:/Manga" and restart the server

**Comment by hell1231** [comment]
> you change "server.downloadsPath" in the config file to "D:/Manga" and restart the server

that's the download path not the local folder path

**Comment by schroda** [comment]
https://github.com/Suwayomi/Tachidesk-Server/wiki/Configuring-Tachidesk-Server#overriding-tachidesk-servers-data-directory-path

**Comment by hell1231** [comment]
> https://github.com/Suwayomi/Tachidesk-Server/wiki/Configuring-Tachidesk-Server#overriding-tachidesk-servers-data-directory-path

i really tried to understand this page but coudn't figure this out
like, where do i put the command?

**Comment by hell1231** [comment]
![image](https://github.com/Suwayomi/Tachidesk-WebUI/assets/81326807/ffca718c-dd19-4254-97de-ddc7ea2f4b3a)
tried to make a text file then put the command and edited the file's type to .bat and run it, but didn't work as well...

**Comment by schroda** [comment]
you have to edit the bat file which you are using to start the server, look at the "debug launcher" for an example

**Comment by hell1231** [comment]
> 

![image](https://github.com/Suwayomi/Tachidesk-WebUI/assets/81326807/70642501-ffcc-4d13-84f0-6141fc03ac2e)
tried this, didn't work

**Comment by schroda** [comment]
`jre\bin\java -Dsuwayomi.tachidesk.config.server.rootDir="D:/Manga" -jar  Tachidesk-Server.jar`
