### ISSUE TITLE
[Bug] Library / Downloaded items not updating

### ISSUE THREAD

**Issue by oldShatteredHands7** [Suwayomi/Tachidesk-WebUI#394]
## Device information
- Tachidesk version: v0.7.0
- Operating System: MacOS Ventura 13.4.1 (Client and Server)
- Client JVM version: Java 17.0.7 (and Java 11 too)
- Server JVM version: Java 17.0.7 (and Java 11 too)
- Client Web Browser: Safari 16.5.1 / Brave 1.52.129
## Steps to reproduce

1. Download a manga
2. Verify content is located in /Users/<username>/Library/Application Support/Tachidesk/downloads/MangaReader (JA)/<manga>/<chapter>
3. Verify that manga is in state "downloaded" by browsing through the Sources menu
4. Open "Library" menu to see "Your Library is empty". Clicking the refresh button will just keep showing 0%

### Expected behavior
Library menu should contain the downloaded content

### Actual behavior
Content is not displayed although files (JPEGS) exist on disk and manga is in state downloaded in Sources menu

## Other details
Only output of the console log is
11:05:40.277 [JettyServerThreadPool-41] INFO  suwayomi.tachidesk.manga.impl.update.UpdaterSocket - 227b7289-415c-44d9-b292-a83125f9b191
11:06:18.549 [JettyServerThreadPool-55] INFO  suwayomi.tachidesk.manga.controller.UpdateController - Adding Library to Update Queue

**Comment by schroda** [comment]
You have to add the manga to your library for it to show up there

**Comment by oldShatteredHands7** [comment]
> You have to add the manga to your library for it to show up there

Thanks. I just started debugging and noticed that I was missing exactly that
