### ISSUE TITLE
[Bug] Empty page when loading manga without source extension

### ISSUE THREAD

**Issue by qu1ck** [Suwayomi/Tachidesk-WebUI#428]
This is exactly like https://github.com/Suwayomi/Tachidesk-WebUI/issues/284

So either this bug has resurfaced or the latest server preview docker image bundles old webui.

## Device information
- Tachidesk version: v0.7.0-r1393 Build time Tue, 17 Oct 2023 00:14:24 GMT
- Server Operating System: docker image on linux
- Server Desktop Environment: N/A
- Server JVM version: bundled with docker image
- Client Operating System: <usually the same as above Server Operating System>
- Client Web Browser: current chrome

## Steps to reproduce
Remove an extension from server, load manga you previously had sourced from it.

### Expected behavior
Manga still shows

### Actual behavior
White screen

## Other details
Error from dev tools console:
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'displayName')
    at tr (MangaDetails.tsx:120:16)
    at oi (react-dom.production.min.js:157:137)
    at Gc (react-dom.production.min.js:267:460)
    at El (react-dom.production.min.js:250:347)
    at kl (react-dom.production.min.js:250:278)
    at Sl (react-dom.production.min.js:250:138)
    at ml (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Uo (react-dom.production.min.js:122:325)
```

**Comment by schroda** [comment]
with the server preview the webUI gets updated automatically, but the default channel is `stable`.
the stable version is outdated and if you want the latest version you should change it to `preview`

**Comment by qu1ck** [comment]
`webUIChannel` is not documented in that wiki (or in the settings file that is first created by server)

I added `server.webUIChannel = "preview"` but I have no idea if it did anything, is there a way to check the version of the webui?

**Comment by schroda** [comment]
in the root dir of the server (https://github.com/Suwayomi/Tachidesk-Server/wiki/The-Data-Directory) is a `webUI` folder and in that folder is a `revision` file which contains the webUI version

> webUIChannel is not documented in that wiki (~~or in the settings file that is first created by server~~)

was it in the config file? if not that is another issue (server side), because with the preview version of the server, it should be kept up-to-date

**Comment by qu1ck** [comment]
Yes, I found the setting in the config file later, hence the strike out text.
But another problem I ran into is that after the restart the server reverts it back to "stable". 

The revision file says `r983` which sounds old (if it's commit counter).

**Comment by schroda** [comment]
> But another problem I ran into is that after the restart the server reverts it back to "stable".

if you updated it to "preview" in the config and restarted the server after that and it's not working it would be an issue for the server (https://github.com/Suwayomi/Tachidesk-Server/issues)

**Comment by qu1ck** [comment]
Thanks, filed https://github.com/Suwayomi/Tachidesk-Server/issues/740
