### ISSUE TITLE
[Bug] manga search query containing % (percentage char) never completes

### ISSUE THREAD

**Issue by qu1ck** [Suwayomi/Tachidesk-WebUI#448]
## Device information
- Tachidesk version: v0.7.0-r1417
- Server Operating System: docker image on linux host
- Server Desktop Environment: N/A
- Server JVM version: bundled with docker image
- Client Operating System: Windows 10
- Client Web Browser: chrome 119.0.6045.106

Web UI version: r1245

## Steps to reproduce
1. Go to browse section and enter a search query containing percentage sign, for example "100%"

### Expected behavior
Query should complete

### Actual behavior
Query never completes

## Other details
Browser dev console shows a bunch of graphql queries with errors:
`URLDecoder: Illegal hex characters in escape (%) pattern - Error at index 0 in: "","`

On alternative UI (tachidesk sorayomi) it completes and returns valid results

**Comment by qu1ck** [comment]
Any comment to why was this closed? Did I open it in the wrong repo?

**Comment by Syer10** [comment]
It's fixed in the latest Tachidesk-Server 👍

**Comment by qu1ck** [comment]
Thanks for the [fix](https://github.com/Suwayomi/Tachidesk-Server/commit/50cd0c4e108256d88760a073e45f095ca32a0303)
