### ISSUE TITLE
[Feature Request] Download All Chapters

### ISSUE THREAD

**Issue by xyzeratul** [Suwayomi/Tachidesk-WebUI#63]
## What feature should be added to Tachidesk?
A "Download All Chapters" option add in main library page for each manga, or in the manga info page.

##  Why/Project's Benefit/Existing Problem
This will greatly help people like to download all chapters before reading, but click on each chapter and download them one by one is too frustrated and would easily miss 1 or 2 chapters.

**Comment by Robonau** [comment]
covered by #17

**Comment by AriaMoradi** [comment]
oops

**Comment by onmyouji** [comment]
In addition to 'download all', it would also be great if there's an option to select multiple chapters (e.g. using checkbox), so that users can download multiple selected chapters.

**Comment by martinek** [comment]
This should now be possible through manga page.

@AriaMoradi also fixed by #194
