### ISSUE TITLE
[Feature Request] Better looking download queue list items

### ISSUE THREAD

**Issue by AriaMoradi** [Suwayomi/Tachidesk-WebUI#64]
## What feature should be added to Tachidesk?
After https://github.com/Suwayomi/Tachidesk-Server/pull/244 we can finally show a card similar to Tachiyomi, something like `Updates` cards would be nice.

##  Why/Project's Benefit/Existing Problem
Copy Tachiyomi even more.

**Comment by Robonau** [comment]
#138 did this
